spring:
  datasource:
    url: jdbc:postgresql://${db_host}:${db_port}/${db_database}
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect