spring:
  datasource:
    url: jdbc:mysql://${host}:${port}/${database}
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect